kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ray-workflows-claim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ .Values.storage.storageClassName | default "default" }}