# Ray worker docker-compose configuration

version: "3"

services:
  worker:
    image: ${SYNTHO_RAY_IMAGE}
    restart: always
    network_mode: host
    container_name: ray-worker
    shm_size: 4gb
    environment:
       RAY_SCHEDULER_SPREAD_THRESHOLD: 0.0
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: >
      ray start --address=${RAY_HEAD_IP}:6379 --block --disable-usage-stats