apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.core.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "syntho-core.labels" . | nindent 4 }}
    app: {{ .Values.core.name }}
  name: {{ .Values.core.name }}
spec:
  replicas: {{ .Values.core.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.core.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.core.name }}
    spec:
      containers:
        - image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}"
          env:
            - name: APP_ENV
              value: {{ .Values.core.app_env | default "prod" }}
            - name: DATABASE_URL
              value: "postgresql+asyncpg://{{ .Values.core.db.username }}:{{ .Values.core.db.password }}@{{ .Values.core.db.host }}:{{ .Values.core.db.port | default "5432" }}/{{ .Values.core.db.name }}"
            - name: PORT
              value: {{quote .Values.core.port }}
            - name: SECRET_KEY
              value: {{quote .Values.core.secret_key }}
            - name: WORKER_TIMEOUT
              value: "{{ .Values.core.worker_timeout | default "3000" }}"
            - name: SECRET_KEY_2
              value: {{quote .Values.core.secret_key }}
            - name: CELERY_BROKER_URL
              value: {{quote .Values.core.redis_host }}
            - name: CELERY_RESULT_BACKEND
              value: {{quote .Values.core.redis_host }}
            - name: RAY_ADDRESS
              value: {{quote .Values.core.ray_address }}
            - name: LICENSE_KEY_SIGNED
              value: {{ .Values.SynthoLicense }}
          {{- if or $.Values.core.env $.Values.core.envSecrets }}
            {{- range $key, $value := $.Values.core.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $secret := $.Values.core.envSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret }}
                  key: {{ $key | quote }}
            {{- end }}
          {{- end }}
          name: {{ .Values.core.name }}
          volumeMounts:
            {{- toYaml .Values.core.volumeMounts | default "" | nindent 12 }} 
          ports:
            - containerPort: {{ .Values.core.port }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "3Gi"
            requests:
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: {{ .Values.core.port }}
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: {{ .Values.core.port }}
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 2
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- toYaml .Values.core.volumes | default "" | nindent 8 }}    
      restartPolicy: Always
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- .Values.affinity | toYaml | nindent 8 }}
      {{- end }}
status: {}
